# Generated by Django 4.2.29 on 2026-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/featured/'),
        ),
    ]
